#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SCREEN_SCALE 2

#define SCREEN_WIDTH_SIZE (SCREEN_WIDTH/SCREEN_SCALE)
#define SCREEN_HEIGHT_SIZE (SCREEN_HEIGHT/SCREEN_SCALE)

